spring.application.name=compras-api

spring.datasource.url=jdbc:mysql://localhost:3306/compras2_0?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=Joao06062007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080